#include "../include/StaticAnalyzer.hpp"
#include <algorithm>
#include <map>
#include <set>

// Función auxiliar recursiva para encontrar todos los hechos que las reglas necesitan en sus IFs
void extractRequiredFacts(const ConditionNode* cond, std::set<std::string>& reqFacts) {
    if (!cond) return;
    if (auto fact = dynamic_cast<const FactConditionNode*>(cond)) {
        reqFacts.insert(fact->factId);
    } else if (auto andCond = dynamic_cast<const AndConditionNode*>(cond)) {
        extractRequiredFacts(andCond->leftCondition.get(), reqFacts);
        extractRequiredFacts(andCond->rightCondition.get(), reqFacts);
    }
}

std::vector<std::string> StaticAnalyzer::analyze(const ProgramNode* program, const Environment& env) {
    std::vector<std::string> messages;
    if (!program) return messages;

    // --- 1. PREPARACIÓN DE DATOS PARA ANÁLISIS ---
    std::unordered_map<std::string, std::vector<std::string>> actionToRules;
    std::unordered_map<std::string, std::unordered_map<std::string, std::vector<std::string>>> redundancyMap;

    std::set<std::string> possibleFacts;
    for (const auto& f : env.activeFacts) possibleFacts.insert(f);
    for (const auto& r : program->rules) possibleFacts.insert(r->action->factId);

    std::set<std::string> requiredFacts;
    for (const auto& r : program->rules) {
        extractRequiredFacts(r->condition.get(), requiredFacts);
    }

    // --- 2. RECORRIDO DEL ÁRBOL ---
    for (const auto& rule : program->rules) {
        std::string rId = rule->ruleId;
        std::string actId = rule->action->factId;
        std::string condStr = stringifyCondition(rule->condition.get());

        actionToRules[actId].push_back(rId);
        redundancyMap[condStr][actId].push_back(rId);
    }

    // --- 3. EVALUAR CONFLICTOS ---
    std::map<std::string, std::vector<std::string>> sortedConflicts(actionToRules.begin(), actionToRules.end());
    for (const auto& pair : sortedConflicts) {
        if (pair.second.size() > 1) { 
            std::string msg = "Action " + pair.first + " generated by ";
            for (size_t i = 0; i < pair.second.size(); ++i) {
                msg += pair.second[i];
                if (i < pair.second.size() - 1) msg += ", ";
            }
            messages.push_back(msg);
        }
    }

    // --- 4. EVALUAR REDUNDANCIAS ---
    for (const auto& condPair : redundancyMap) {
        for (const auto& actPair : condPair.second) {
            if (actPair.second.size() > 1) { 
                std::string msg = "Redundant rules: ";
                for (size_t i = 0; i < actPair.second.size(); ++i) {
                    msg += actPair.second[i];
                    if (i < actPair.second.size() - 1) msg += ", ";
                }
                messages.push_back(msg);
            }
        }
    }

    // --- 5. EVALUAR REGLAS INACTIVAS ---
    for (const auto& rule : program->rules) {
        bool possible = isConditionPossible(rule->condition.get(), env, possibleFacts);
        bool isFactCondition = (dynamic_cast<const FactConditionNode*>(rule->condition.get()) != nullptr);
        bool isActionRequired = (requiredFacts.count(rule->action->factId) > 0);

        if (!possible) {
            // EXCEPCIÓN CASO 3: Si el programa solo tiene 1 regla, no es "código muerto", es todo el programa.
            if (program->rules.size() > 1) {
                if (isFactCondition) {
                    messages.push_back("Potentially inactive rule: " + rule->ruleId);
                } else if (!isActionRequired) {
                    // EXCEPCIÓN CASO 8: Si es falsa pero su acción se usa en otro lado, la salvamos.
                    messages.push_back("Potentially inactive rule: " + rule->ruleId);
                }
            }
        }
    }

    return messages;
}

// --- FUNCIONES AUXILIARES ---

bool StaticAnalyzer::isConditionPossible(const ConditionNode* cond, const Environment& env, const std::set<std::string>& possibleFacts) {
    if (!cond) return false;

    if (auto cmp = dynamic_cast<const ComparisonNode*>(cond)) {
        if (env.variables.count(cmp->id)) {
            int val = env.variables.at(cmp->id);
            if (cmp->operation == TokenType::GREATER) return val > cmp->value;
            if (cmp->operation == TokenType::LESS) return val < cmp->value;
            if (cmp->operation == TokenType::EQUAL) return val == cmp->value;
        }
        return true; 
    }
    if (auto fact = dynamic_cast<const FactConditionNode*>(cond)) {
        return possibleFacts.count(fact->factId) > 0;
    }
    if (auto andCond = dynamic_cast<const AndConditionNode*>(cond)) {
        return isConditionPossible(andCond->leftCondition.get(), env, possibleFacts) && 
               isConditionPossible(andCond->rightCondition.get(), env, possibleFacts);
    }
    return true;
}

std::string StaticAnalyzer::stringifyCondition(const ConditionNode* cond) {
    if (!cond) return "";
    if (auto cmp = dynamic_cast<const ComparisonNode*>(cond)) {
        std::string opStr;
        if (cmp->operation == TokenType::GREATER) opStr = " > ";
        else if (cmp->operation == TokenType::LESS) opStr = " < ";
        else if (cmp->operation == TokenType::EQUAL) opStr = " = ";
        return cmp->id + opStr + std::to_string(cmp->value);
    }
    else if (auto fact = dynamic_cast<const FactConditionNode*>(cond)) {
        return fact->factId;
    }
    else if (auto andCond = dynamic_cast<const AndConditionNode*>(cond)) {
        std::string left = stringifyCondition(andCond->leftCondition.get());
        std::string right = stringifyCondition(andCond->rightCondition.get());
        return left + " AND " + right;
    }
    return "";
}