//Include of all the required programs
#include "../include/StaticAnalyzer.hpp"
#include <algorithm>
#include <map>

std::vector<std::string> StaticAnalyzer::analyze(const ProgramNode* program) {
    std::vector<std::string> messages;
    if (!program) return messages;

    //Data structure to track redundancies and conflicts
    //"name of the action" -> Name list of the rules that generate it
    std::unordered_map<std::string, std::vector<std::string>> actionToRules;
    
    //"ConditionString" -> Map: "ActionString" -> List of rules
    //Allows to detect rules with the same condition and action
    std::unordered_map<std::string, std::unordered_map<std::string, std::vector<std::string>>> redundancyMap;

    //Traveling the entire AST tree
    for (const auto& rule : program->rules) {
        std::string rId = rule->ruleId;
        std::string actId = rule->action->factId;
        std::string condStr = stringifyCondition(rule->condition.get());

        //Track actions to detect conflicts
        actionToRules[actId].push_back(rId);

        //Track (condition + action) to detect redundancies
        redundancyMap[condStr][actId].push_back(rId);
    }

    //Evaluate conflicts
    std::map<std::string, std::vector<std::string>> sortedConflicts(actionToRules.begin(), actionToRules.end());
    for (const auto& pair : sortedConflicts) {

        if (pair.second.size() > 1) { //More than one rules generates this action
            std::string msg = "Action " + pair.first + " generated by ";

            for (size_t i = 0; i < pair.second.size(); ++i) {
                msg += pair.second[i];
                if (i < pair.second.size() - 1) msg += ", ";
            }

            messages.push_back(msg);
        }
    }

    //Evaluate redundancy
    for (const auto& condPair : redundancyMap) {
        for (const auto& actPair : condPair.second) {
            if (actPair.second.size() > 1) { //More than one rule looks the same
                std::string msg = "Redundant rules: ";
                for (size_t i = 0; i < actPair.second.size(); ++i) {
                    msg += actPair.second[i];
                    if (i < actPair.second.size() - 1) msg += ", ";
                }
                messages.push_back(msg);
            }
        }
    }

    //5. Evaluate potentially inactive rules
    for (const auto& rule : program->rules) {
        //Obtain all the tokens that generate that certain rule
        std::string condStr = stringifyCondition(rule->condition.get());
    }

    return messages;
}

//Transform the tree to make it easier the syntactical analysis and math comparisons
std::string StaticAnalyzer::stringifyCondition(const ConditionNode* cond) {
    if (!cond) return "";

    //Cerifications for comparisons
    if (auto cmp = dynamic_cast<const ComparisonNode*>(cond)) {
        std::string opStr;
        if (cmp->operation == TokenType::GREATER) opStr = " > ";
        else if (cmp->operation == TokenType::LESS) opStr = " < ";
        else if (cmp->operation == TokenType::EQUAL) opStr = " = ";
        return cmp->id + opStr + std::to_string(cmp->value);
    }
    //Verification for facts
    else if (auto fact = dynamic_cast<const FactConditionNode*>(cond)) {
        return fact->factId;
    }
    //Verification for an AND
    else if (auto andCond = dynamic_cast<const AndConditionNode*>(cond)) {
        std::string left = stringifyCondition(andCond->leftCondition.get());
        std::string right = stringifyCondition(andCond->rightCondition.get());
        return left + " AND " + right;
    }

    return "";
}